using Algorithms.CodeChallenges;

// BinaryGap.Execute();
// ReverseString.Execute();
// Anagram.Execute();
// FirstUniqueChar.Execute();
// BuySellStock.Execute();
// ContainsDuplicates.Execute();
// FizzBuzz.Execute();
// SingleNumber.Execute();
// CyclicRotation.Execute();
// OddOccurrences.Execute();
// ValidParenthesis.Execute();
// PowerOfTwo.Execute();
// Fibonacci.Execute();
// Factorial.Execute();
// Subset.Execute();
// NumberOfIslands.Execute();
// TwoNumbers.Execute();
// PeakElement.Execute();
// ReverseInteger.Execute();
// BackspaceStringCompare.Execute();
// MinWindowSubstring.Execute();
// NonrepeatingCharacter.Execute();
// FirstBadVersion.Execute();
// PaintHouse.Execute();
// MoveZeroes.Execute();
BinarySearchTree.Execute();